### ISSUE TITLE
Safari Plus marked as compatible when it isn't

### ISSUE THREAD

**Issue by nathanielcwm** [Samgisaninja/tweakcompatible-zebra#2]
Safari Plus 1.6.8-3 is marked as compatible when it isn't.
![7265858C-488A-4BD0-970A-9B58AF8FC8E9](https://user-images.githubusercontent.com/22572406/62336449-efd84180-b502-11e9-82a2-9a045925d1f3.png)
![87E1A4C8-9382-4A0E-9C84-06049A53A4F5](https://user-images.githubusercontent.com/22572406/62336450-efd84180-b502-11e9-85e6-dd2e03c4d484.png)
![A2A448E4-C2D4-4628-8571-6517A32D73A8](https://user-images.githubusercontent.com/22572406/62336451-f070d800-b502-11e9-9fc1-8a2f07a769a1.png)
It works normally in tweakcompatible
![5140F251-55B4-4421-B901-0DE855E78E8D](https://user-images.githubusercontent.com/22572406/62336460-fbc40380-b502-11e9-959b-ae1f39a8ea10.png)

**Comment by Samgisaninja** [comment]
yeah--the data it's providing is based on the latest version, not the installed version.

Version 1.7 from opa334's repo works, but version 1.6.8-3 doesn't.

Since you don't have opa334's repo in your source list, it shows the version available to you as compatible, even though it actually isn't. 

I'll probably fix this by checking the installed version instead of the remote version.
